{% set name = "pysimplecache" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/{{ name|lower }}/archive/refs/tags/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 5a9fca7abd283b7825f74ad2d293fe99ca5105a34b98039714dee49d68ec4a05

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python }}
  run:
    - python {{ python }}

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
    - {{ name|lower }}.tests
  requires:
    - pytest
    - pytest-cov
  commands:
    - pytest -v --cov --cov-report term-missing

about:
  home: https://github.com/brsynth/{{ name|lower }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A simple cache of objects'
  description: |
    pysimplecache is a simple cache to store
    (in a non-persistent way) and share objects of any type.
  dev_url: https://github.com/brsynth/pysimplecache

extra:
  recipe-maintainers:
    - breakthewall
