{% set name = "pysbol" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/pySBOL/archive/{{ version }}.tar.gz
  sha256: 65d79b956e1249370307bc2a1e8638f776bd10b0559a6ab507477a65bcedc74c

build:
  number: 0
  script: {{ PYTHON }} -m pip install -vv .
  binary_relocation: true
  missing_dso_whitelist:
    - $RPATH/_libsbol.so
    - $RPATH/libxml2-8ed442f7.so.2.6.26
    - $RPATH/libz-a147dcb0.so.1.2.3
    - $RPATH/libxslt-6cbe83bf.so.1.1.17
    - /lib64/libc.so.6
    - /lib64/libm.so.6
    - /lib64/libdl.so.2
    - /lib64/libm.so.6
    - 'libstdcxx-ng'
    - 'libgcc-ng'
    - lib/libstdc++
    - lib/libgcc_s.so.1
    - lib/libstdc++.so.6
  skip: true  # [win]

requirements:
  host:
    - python =3.7
    - pip
  run:
    - python =3.7
    - requests

test:
  source_files:
    - tests
  imports:
    - pysbol
  requires:
    - pytest
  commands:
    - cd tests
    - pytest -v

about:
  home: https://github.com/brsynth/pySBOL/
  summary: A module for reading, writing, and constructing genetic designs according to the standardized specifications of the Synthetic Biology Open Language (SBOL).
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - breakthewall
    - kenza12
