{% set name = "pysbol" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SynBioDex/pySBOL/archive/{{ version }}.tar.gz
  sha256: 153432071fdba11ad3612c183f589bee8d9855d088203d5be8832c8026c4e5ec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python =3.7
    - pip
  run:
    - python =3.7
    - libxslt
    - requests

test:
  imports:
    - sbol

about:
  home: https://github.com/SynBioDex/{{ name|lower }}
  summary: A module for reading, writing, and constructing genetic designs according to the standardized specifications of the Synthetic Biology Open Language (SBOL).
  license: Apache
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - breakthewall
    - kenza12
