{% set name = "pysbol" %}
{% set version = "2.3.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SynBioDex/pySBOL/archive/{{ version }}.tar.gz
  sha256: e44ec21341a3131808f8cc2c2b33262e2a3faf23bd9bb605ab4ffa9e40d0a4f7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python =3.7
    - pip
  run:
    - python =3.7
    - libxslt
    - requests

test:
  imports:
    - sbol

about:
  home: https://github.com/SynBioDex/pySBOL
  summary: A module for reading, writing, and constructing genetic designs according to the standardized specifications of the Synthetic Biology Open Language (SBOL).
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - breakthewall
    - kenza12
