{% set name = "simplecache" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/{{ name|lower }}/archive/refs/tags/{{ name|lower }}-{{ version }}.tar.gz
  sha256: a78fce4bb81883cb359dfe39013cd578be8b07f797891df6a69874208e5a69f7

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
  run:
    - python >=3.6

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
    - {{ name|lower }}.tests
  requires:
    - pytest
    - pytest-cov
  commands:
    - pytest -v --cov --cov-report term-missing

about:
  home: https://github.com/brsynth/{{ name|lower }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A simple cache of objects'
  description: |
    simplecache is a simple cache to store
    (in a non-persistent way) and share objects of any type.
  dev_url: https://github.com/brsynth/simplecache

extra:
  recipe-maintainers:
    - breakthewall
